_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth:9999
    routes:
      - name: auth-route
        paths:
          - /auth/v1

  - name: rest-service
    url: http://rest:3000
    routes:
      - name: rest-route
        paths:
          - /rest/v1

  - name: storage-service
    url: http://storage:5000
    routes:
      - name: storage-route
        paths:
          - /storage/v1

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:4200
        - http://localhost:4201
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - X-Client-Info
      exposed_headers:
        - X-Total-Count
      credentials: true
      max_age: 3600